name = "todolist"
account_id = "3adb6783a9b30e9f7f2c36c3a3ba7bf9"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[[d1_databases]]
binding = "DB"
database_name = "todolist-db"
database_id = "15668e96-49bd-4086-a93b-a5f282e5db91"

[vars]
APP_URL = "https://todolist.fullstackjam.com"
